# Generated by Django 2.1.2 on 2019-02-01 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_auto_20190201_0737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='url',
            field=models.CharField(default='НЕТ', max_length=200, verbose_name='Адрес ссылки'),
        ),
    ]
